Blog/Controllers/ArticlesController.cs
using Blog.Models.Domain;
using Blog.Models.ViewModels;
using Blog.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Blog.Controllers
{

    [Authorize(Roles = "Admin")]
    public class ArticlesController : Controller
    {
        private readonly ITagRepository tagRepository;
        private readonly IArticleRepository articleRepository;
        private readonly ILogger<ArticlesController> _logger;
        public ArticlesController(ITagRepository tagRepository, IArticleRepository articleRepository, ILogger<ArticlesController> logger)
        {
            this.tagRepository = tagRepository;
            this.articleRepository = articleRepository;
            _logger = logger;
            _logger.LogDebug(1, "NLog подключен к ArticlesController");
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var tags = await tagRepository.GetAllAsync();

            var model = new AddArticleViewModel
            {
                Tags = tags.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() })
            };
            _logger.LogInformation("ArticlesController - обращение к методу Add");
            return View(model);

        }

        [HttpPost]
        public async Task<IActionResult> Add(AddArticleViewModel addArticleViewModel)
        {

            var article = new Article
            {
                Heading = addArticleViewModel.Heading,
                PageTitle = addArticleViewModel.PageTitle,
                Content = addArticleViewModel.Content,
                ShortDescription = addArticleViewModel.ShortDescription,
                FeaturedImageUrl = addArticleViewModel.FeaturedImageUrl,
                UrlHandle = addArticleViewModel.UrlHandle,
                PublishedDate = addArticleViewModel.PublishedDate,
                Author = addArticleViewModel.Author,
                Visible = addArticleViewModel.Visible,
            };


            var selectedTags = new List<Tag>();

            foreach (var selectedTagId in addArticleViewModel.SelectedTags)
            {
                var selectedTagIdAsGuid = Guid.Parse(selectedTagId);
                var existingTag = await tagRepository.GetAsync(selectedTagIdAsGuid);

                if (existingTag != null)
                {
                    selectedTags.Add(existingTag);
                }
            }

            article.Tags = selectedTags;

            await articleRepository.AddAsync(article);
            _logger.LogInformation("ArticlesController - обращение к методу Add");
            return RedirectToAction("Add");
        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            var articles = await articleRepository.GetAllAsync();
            _logger.LogInformation("ArticlesController - обращение к методу List");
            return View(articles);
        }


        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var article = await articleRepository.GetAsync(id);
            var tagsDomainModel = await tagRepository.GetAllAsync();

            if (article != null)
            {
                var model = new EditArticleViewModel
                {
                    Id = article.Id,
                    Heading = article.Heading,
                    PageTitle = article.PageTitle,
                    Content = article.Content,
                    ShortDescription = article.ShortDescription,
                    FeaturedImageUrl = article.FeaturedImageUrl,
                    UrlHandle = article.UrlHandle,
                    PublishedDate = article.PublishedDate,
                    Author = article.Author,
                    Visible = article.Visible,
                    Tags = tagsDomainModel.Select(x => new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    }),
                    SelectedTags = article.Tags.Select(x => x.Id.ToString()).ToArray()
                };
                _logger.LogInformation("ArticlesController - обращение к методу Edit");
                return View(model);
            }
            _logger.LogInformation("ArticlesController - обращение к методу Edit");
            return View(null);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditArticleViewModel editArticleViewModel)
        {

            var articleDomainModel = new Article
            {
                Id = editArticleViewModel.Id,
                Heading = editArticleViewModel.Heading,
                PageTitle = editArticleViewModel.PageTitle,
                Content = editArticleViewModel.Content,
                ShortDescription = editArticleViewModel.ShortDescription,
                FeaturedImageUrl = editArticleViewModel.FeaturedImageUrl,
                UrlHandle = editArticleViewModel.UrlHandle,
                PublishedDate = editArticleViewModel.PublishedDate,
                Author = editArticleViewModel.Author,
                Visible = editArticleViewModel.Visible
            };

            var selectedTags = new List<Tag>();
            foreach (var selectedTag in editArticleViewModel.SelectedTags)
            {
                if (Guid.TryParse(selectedTag, out var tag))
                {
                    var foundTag = await tagRepository.GetAsync(tag);

                    if (foundTag != null)
                    {
                        selectedTags.Add(foundTag);
                    }
                }

            }

            articleDomainModel.Tags = selectedTags;

            var updatedArticle = await articleRepository.UpdateAsync(articleDomainModel);

            if (updatedArticle != null)
            {
                _logger.LogInformation("ArticlesController - обращение к методу Edit");
                return RedirectToAction("List");
            }
            _logger.LogInformation("ArticlesController - обращение к методу Edit");
            return RedirectToAction("Edit");
        }


        [HttpPost]
        public async Task<IActionResult> Delete(EditArticleViewModel editArticleViewModel)
        {
            var deletedArticle = await articleRepository.DeleteAsync(editArticleViewModel.Id);

            if (deletedArticle != null)
            {
                _logger.LogInformation("ArticlesController - обращение к методу Delete");
                return RedirectToAction("List");
            }
            _logger.LogInformation("ArticlesController - обращение к методу Delete");
            return RedirectToAction("Edit", new { id = editArticleViewModel.Id });
        }


        [HttpGet]
        public async Task<IActionResult> GetArticlesByAuthor(string userName)
        {
            
            var articles = await articleRepository.GetArticlesByAuthorAsync(userName);
            _logger.LogInformation("ArticlesController - обращение к методу GetArticlesByAuthor");
            return View(articles);
        }
    }
}

Blog/Controllers/RolesController.cs
using Blog.Models.ViewModels;
using Blog.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Controllers
{

    [Authorize(Roles = "Admin")]
    public class RolesController : Controller
    {

        private readonly IRoleRepository roleRepository;
        private readonly ILogger<RolesController> _logger;

        public RolesController(IRoleRepository roleRepository, ILogger<RolesController> logger)
        {
            this.roleRepository = roleRepository;
            _logger = logger;
            _logger.LogDebug(1, "NLog подключен к RolesController");

        }
        [HttpGet]
        public async Task<IActionResult> List()
        {
            var roles = await roleRepository.GetAll();

            var rolesViewModels = new List<RoleViewModel>();

            foreach (var role in roles)
            {
                var roleViewModel = new RoleViewModel
                {
                    Id = Guid.Parse(role.Id),
                    Name = role.Name
                };

                rolesViewModels.Add(roleViewModel);
            }


            _logger.LogInformation("RolesController - обращение к методу List");
            return View(rolesViewModels);
        }
    }
}

Blog/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Blog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Blog.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <link href='https://cdn.jsdelivr.net/npm/froala-editor@latest/css/froala_editor.pkgd.min.css' rel='stylesheet' type='text/css' />
    <script type='text/javascript' src='https://cdn.jsdelivr.net/npm/froala-editor@latest/js/froala_editor.pkgd.min.js'></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Blog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin")){

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Admin
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Tags" asp-action="Add">Add Tag</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Tags" asp-action="List">Show All Tags</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Articles" asp-action="Add">Add Article</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Articles" asp-action="List">Show All Articles</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Articles" asp-action="GetArticlesByAuthor" asp-route-userName="admin1@blog.com">Show All Admin's Articles</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Articles" asp-action="GetArticlesByAuthor" asp-route-userName="superadmin@blog.com">Show All Super Admin's Articles</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Users" asp-action="List">Show All Users</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Comments" asp-action="List">Show All Comments</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Roles" asp-action="List">Show All Roles</a></li>
                                </ul>
                            </li>
                        }

                    </ul>

                    <div class="d-flex align-items-center">

                        @if (signInManager.IsSignedIn(User))
                        {
                            <div class="me-3 text-light">
                                @User?.Identity?.Name
                            </div>

                            <a class=" btn me-3 bg-light text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                        }
                        else
                        {
                            <a class=" btn me-3 bg-light text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            <a class=" btn me-3 bg-light text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        }

                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Blog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>